language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database diy_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: VMdm/EF4kdGp4qzVlj5+9qa5cK4I9lKtV79Ys8AgCYH7A93uD84wYlOjFM+S268mjJpq4V7hvzorMNgP+szSHZlG8eNr5W9lZX5nl9/9sh9Jomu/VaWOyCQeEho79OxWYLxmpbDlXe0F0lms9l54aJ79Dhj3fhliJqWSYuf89EE=
  app: ancient-inlet-9686
  run:
    - "rake db:migrate"
    - restart
  on:
    branch: master
    rvm: 1.9.3
    repo: zachgersh/pbp
